### ISSUE TITLE
Catalog Display Typo (Space After Bullet Point Marker is Needed)

### ISSUE THREAD

**Issue by rollandlee** [MadailicaiTech/Wechat-Summary#2]
As the image tell
![screen shot 2016-04-25 at 5 16 19 pm](https://cloud.githubusercontent.com/assets/1026249/14779182/7b6cc77c-0b09-11e6-8b46-d0e29433d92d.png)

**Comment by grissomsh** [comment]
It works now, please have a check, thanks.
